Riverside/urls.py
from django.contrib import admin
from django.urls import path, include
from alquileres_eventos import views as alquileres_eventos_views
from users import views as users_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('alquileresyeventos/',include('alquileres_eventos.urls')),
    path('clientesysocios/',include('clientes_socios.urls')),
    path('users/', include('users.urls')),

    path('',alquileres_eventos_views.home, name='home'),
    path('register', users_views.registrar_usuario,name='register'),
    path('login', users_views.login_usuario, name= 'login'),
    path('logout', users_views.salir, name='logout'),
]

alquileres_eventos/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from .views import *

app_name='alquileres_eventos'

urlpatterns = [
    path('servicios/',ListarServicios.as_view(template_name="alquileres_eventos/servicios_list.html"),name="servicios-list"),
    path('crear_servicio/', añadirServicio,name="servicio-create"),
    path('detalle_servicio/<int:pk>', ServicioDetalle.as_view(template_name="alquileres_eventos/servicio_detalle.html"),name="servicio-detalle"),
    path('actualizar_servicio/<int:pk>', actualizarServicio, name="servicio-editar"),
    path('eliminar_servicio/<int:pk>', ServicioEliminar.as_view(),name="servicio-eliminar"),

    path('sectores/',ListarSectores.as_view(template_name="alquileres_eventos/sectores_list.html"),name="sectores-list"),
    path('crear_sector/', añadirSector,name="sector-create"),
    path('detalle_sector/<int:pk>', SectorDetalle.as_view(template_name="alquileres_eventos/sector_detalle.html"),name="sector-detalle"),
    path('actualizar_sector/<int:pk>', actualizarSector, name="sector-editar"),
    path('eliminar_sector/<int:pk>', SectorEliminar.as_view(),name="sector-eliminar"),

    path('eventos/',ListarEventos.as_view(template_name="alquileres_eventos/eventos_list.html"),name="eventos-list"),
    path('crear_evento/<int:cedula>', RegistrarEvento.as_view(template_name="alquileres_eventos/evento_form.html"),name="evento-create"),
    path('detalle_evento/<int:pk>', EventoDetalle.as_view(template_name="alquileres_eventos/evento_detalle.html"),name="evento-detalle"),
    path('actualizar_evento/<int:pk>', EventoActualizar.as_view(template_name="alquileres_eventos/evento_editar.html"), name="evento-editar"),
    path('eliminar_evento/<int:pk>', EventoEliminar.as_view(),name="evento-eliminar"),
]

clientes_socios/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from .views import *

app_name='clientes_socios'

urlpatterns = [
    path('membresias/',ListarMembresias.as_view(template_name="clientes_socios/membresias_list.html"),name="membresias-list"),
    path('crear_membresia/', CrearMembresia.as_view(template_name="clientes_socios/membresia_form.html"),name="membresia-create"),
    path('detalle_membresia/<int:pk>', MembresiaDetalle.as_view(template_name="clientes_socios/membresia_detalle.html"),name="membresia-detalle"),
    path('actualizar_membresia/<int:pk>', MembresiaActualizar.as_view(template_name="clientes_socios/membresia_editar.html"),name="membresia-editar"),
    path('eliminar_membresia/<int:pk>', MembresiaEliminar.as_view(),name="membresia-eliminar"),

    path('socios/',ListarSocios.as_view(template_name="clientes_socios/socios_list.html"),name="socios-list"),
    path('crear_socio/<int:cedula>', CrearSocio.as_view(template_name="clientes_socios/socio_form.html"),name="socio-create"),
    path('detalle_socio/<int:pk>', SocioDetalle.as_view(template_name="clientes_socios/socio_detalle.html"),name="socio-detalle"),
    path('actualizar_socio/<int:pk>', SocioActualizar.as_view(template_name="clientes_socios/socio_editar.html"),name="socio-editar"),
    path('eliminar_socio/<int:pk>', SocioEliminar.as_view(),name="socio-eliminar"),

    path('registrar_cliente/<int:opcion>', RegistrarCliente.as_view(template_name="clientes_socios/cliente_form.html"),name="cliente-create"),
]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from .views import *

app_name='users'

urlpatterns = [
    path('usuarios/', UserListView.as_view(template_name="users/user_list.html"), name='user-lista'),

    # path('lista_roles/',ListarRoles.as_view(template_name="users/roles_list.html"),name="roles-lista"),
    # path('crear_rol/', CrearRol.as_view(template_name="users/rol_form.html"),name="rol-crear"),
    # path('detalle_rol/<int:pk>', RolDetalle.as_view(template_name="users/rol_detalle.html"),name="rol-detalle"),
    # path('actualizar_rol/<int:pk>', RolActualizar.as_view(template_name="users/rol_editar.html"),name="rol-editar"),
    # path('eliminar_rol/<int:pk>', RolEliminar.as_view(),name="rol-eliminar"),

    
    path('<int:pk>/', UserDetailView.as_view(template_name="users/user_detail.html"), name='user-detalle'),
    path('<int:pk>/update', UserUpdateView.as_view(template_name="users/user_update.html"), name='user-editar'),
    path('eliminar_usuarios/<int:pk>', UserEliminar.as_view(),name="user-eliminar"),
    # path('<int:pk>/roles', RolUpdateView.as_view(template_name="users/anadir_rol.html"),
    # name="anadir-rol"),
    path('habilitar/<int:pk>/<int:opcion>/', views.habilitarVista, name="habilitar-staff"),
]

alquileres_eventos/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.urls import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.db import transaction
from django.forms import modelformset_factory, inlineformset_factory
from datetime import date, datetime, timedelta
from decimal import *
from .forms import *
from .models import *
 
def home (request):
    # Si estamos identificados devolvemos la portada
    if request.user.is_authenticated:
        return render(request, 'alquileres_eventos/home.html')

    return redirect('/login')


# VISTAS RELACIONADAS A SERVICIO

class ListarServicios(ListView):

    model = Servicio


class CrearServicio(SuccessMessageMixin,CreateView):
    model = Servicio
    form_class = ServicioCreateForm
    # fields = '__all__'
    success_message = 'Servicio Creado Correctamente !' # Mostramos este Mensaje luego de Crear un Servcio

    def get_context_data(self, **kwargs):
        contexto = super(CrearServicio, self).get_context_data(**kwargs)
        if self.request.POST:
            contexto['precios'] = PreciosFormSet(self.request.POST, prefix='precios')
        else:
            contexto['precios'] = PreciosFormSet(prefix='precios')
        return contexto

    def form_valid(self, form):
        contexto = self.get_context_data()
        precios = contexto['precios']
        with transaction.atomic():
            self.object = form.save()
            if precios.is_valid():
                precios.instance = self.object
                precios.save()
        return super(CrearServicio, self).form_valid(form)

    # Redireccionamos a la vista con la lista de servicios
    def get_success_url(self):        
        return reverse('alquileres_eventos:servicios-list')

def añadirServicio(request):

    PrecioServicioFormSet = modelformset_factory(PrecioServicioMembresia, form=PrecioServicioForm,
     extra=Membresia.objects.all().count(), formset=PreciosBaseFormSet)

    if request.method == "GET":
        servicio_form = ServicioCreateForm()
        formset = PrecioServicioFormSet(queryset=PrecioServicioMembresia.objects.none())
    elif request.method == "POST":
        servicio_form = ServicioCreateForm(request.POST)
        formset = PrecioServicioFormSet(request.POST, request.FILES)

        if servicio_form.is_valid() and formset.is_valid():
            servicio_obj = servicio_form.save()

            for form in formset.cleaned_data:
                if form:
                    monto = form['monto']   
                    membresia = form['membresia']
                    PrecioServicioMembresia.objects.create(monto=monto, membresia=membresia, servicio=servicio_obj)
            return HttpResponseRedirect('../servicios/')
        else:
            messages.add_message(request, messages.ERROR, 'Error!')

    return render(request, 'alquileres_eventos/servicio_form.html', {'servicio_form':servicio_form, 'formset':formset})

def actualizarServicio(request,pk):

    servicio = get_object_or_404(Servicio, id=pk)
    precios_extras = Membresia.objects.all().count() - PrecioServicioMembresia.objects.filter(servicio__id=pk).count()
    PrecioServicioFormSet = modelformset_factory(PrecioServicioMembresia, form=PrecioServicioForm,
     extra=precios_extras, formset=PreciosBaseFormSet)

    if request.method == "GET":
        pk=pk
        servicio_form = ServicioCreateForm(instance=servicio)
        formset = PrecioServicioFormSet(queryset=PrecioServicioMembresia.objects.filter(servicio__id=pk))
    elif request.method == "POST":
        pk=pk
        servicio_form = ServicioCreateForm(request.POST, instance=servicio)
        formset = PrecioServicioFormSet(request.POST, request.FILES)

        if servicio_form.is_valid() and formset.is_valid():
            servicio_obj = servicio_form.save()

            for form in formset.cleaned_data:
                if form:      
                    membresia = form['membresia']
                    if servicio_obj.precios.filter(membresia=membresia).count() == 0:
                        monto = form['monto'] 
                        PrecioServicioMembresia.objects.create(monto=monto, membresia=membresia, servicio=servicio_obj)
            formset.save()
            return HttpResponseRedirect('../servicios/')
        else:
            messages.add_message(request, messages.ERROR, 'Error!')

    return render(request, 'alquileres_eventos/servicio_editar.html', {'servicio_form':servicio_form, 'formset':formset, 'id':servicio.id})


class ServicioDetalle(DetailView): 
    model = Servicio


class ServicioEliminar(SuccessMessageMixin, DeleteView): 
    model = Servicio 
    form = Servicio
    fields = "__all__"     
 
    # Redireccionamos a la página principal luego de eliminar un registro o postre
    def get_success_url(self): 
        success_message = 'Servicio Eliminado Correctamente !'
        messages.success (self.request, (success_message))       
        return reverse('alquileres_eventos:servicios-list')


# VISTAS RELACIONADAS A SECTOR


class ListarSectores(ListView):

    model = Sector

def añadirSector(request):

    PrecioSectorFormSet = modelformset_factory(PrecioSectorMembresia, form=PrecioSectorForm,
     extra=Membresia.objects.all().count(), formset=PreciosBaseFormSet)

    if request.method == "GET":
        sector_form = SectorCreateForm()
        formset = PrecioSectorFormSet(queryset=PrecioSectorMembresia.objects.none())
    elif request.method == "POST":
        sector_form = SectorCreateForm(request.POST)
        formset = PrecioSectorFormSet(request.POST, request.FILES)

        if sector_form.is_valid() and formset.is_valid():
            sector_obj = sector_form.save()

            for form in formset.cleaned_data:
                if form:
                    monto = form['monto']   
                    membresia = form['membresia']
                    PrecioSectorMembresia.objects.create(monto=monto, membresia=membresia, sector=sector_obj)
            return HttpResponseRedirect('../sectores/')
        else:
            messages.add_message(request, messages.ERROR, 'Error!')

    return render(request, 'alquileres_eventos/sector_form.html', {'sector_form':sector_form, 'formset':formset})


def actualizarSector(request,pk):

    sector = get_object_or_404(Sector, id=pk)
    precios_extras = Membresia.objects.all().count() - PrecioSectorMembresia.objects.filter(sector__id=pk).count()
    PrecioSectorFormSet = modelformset_factory(PrecioSectorMembresia, form=PrecioSectorForm,
     extra=precios_extras, formset=PreciosBaseFormSet)

    if request.method == "GET":
        pk=pk
        sector_form = SectorCreateForm(instance=sector)
        formset = PrecioSectorFormSet(queryset=PrecioSectorMembresia.objects.filter(sector__id=pk))
    elif request.method == "POST":
        pk=pk
        sector_form = SectorCreateForm(request.POST, instance=sector)
        formset = PrecioSectorFormSet(request.POST, request.FILES)

        if sector_form.is_valid() and formset.is_valid():
            sector_obj = sector_form.save()

            for form in formset.cleaned_data:
                if form:      
                    membresia = form['membresia']
                    if sector_obj.precios.filter(membresia=membresia).count() == 0:
                        monto = form['monto'] 
                        PrecioSectorMembresia.objects.create(monto=monto, membresia=membresia, sector=sector_obj)
            formset.save()
            return HttpResponseRedirect('../sectores/')
        else:
            messages.add_message(request, messages.ERROR, 'Error!')

    return render(request, 'alquileres_eventos/sector_editar.html', {'sector_form':sector_form, 'formset':formset, 'id':sector.id})


class SectorDetalle(DetailView): 
    model = Sector

class SectorEliminar(SuccessMessageMixin, DeleteView): 
    model = Sector 
    form = Sector
    fields = "__all__"     
 
    # Redireccionamos a la página principal luego de eliminar un registro o postre
    def get_success_url(self): 
        success_message = 'Sector Eliminado Correctamente !'
        messages.success (self.request, (success_message))       
        return reverse('alquileres_eventos:sectores-list')

#EVENTOS
class ListarEventos(ListView):

    model = Evento

class RegistrarEvento(CreateView):
    model = Evento
    form_class = EventoForm
    # success_message = 'Socio Creado Correctamente !'

    def form_valid(self,form):
        self.object = form.save(commit = False)
        cedula = form.cleaned_data['cedula']
        cliente = get_object_or_404(Cliente, cedula=cedula)
        self.object.cliente = cliente

        servicios = form.cleaned_data['servicio']
        sectores = form.cleaned_data['sector']
        es_socio = Socio.objects.filter(cliente=cliente).count()
        if es_socio != 0 :
            membresia = cliente.socio.membresia
            total_servicio = Decimal(0)
            for servicio in servicios:
                monto_servicio=PrecioServicioMembresia.objects.get(servicio=servicio,membresia=membresia).monto
                total_servicio = total_servicio + monto_servicio

            total_sector = Decimal(0)
            for sector in sectores:
                monto_sector=PrecioSectorMembresia.objects.get(sector=sector,membresia=membresia).monto
                total_sector = total_sector + monto_sector
        else:
            total_servicio = Decimal(0)
            for servicio in servicios:
                total_servicio = total_servicio + servicio.precion_normal

            total_sector = Decimal(0)
            for sector in sectores:
                total_sector = total_sector + sector.precion_normal

        total_evento = total_servicio + total_sector

alquileres_eventos/templates/alquileres_eventos/evento_form.html
{% extends 'alquileres_eventos/base.html' %}

{% block extrahead %}       {# Embeds Extra Resources #}

{{ form.media }}            {# Adds date-picker required JS and CSS #}

{% load crispy_forms_tags %}

	
    <style>
        .botones_form{
            margin-top: 10px;
            margin-bottom: 10px;
            display: flex; 
            position: relative; 
            justify-content: center;
        }
    
        h4{
            margin-top: 10px;
        }
    
    </style>
    
        <div class="container medio_forms">
            <h4>Cliente aun no se encuentra registrado? Registralo aqui:</h4>
            <div class="row botones" style="position: relative;">
                <a class="btn btn-dark boton_bordo" id="btn-cliente" href="{% url 'clientes_socios:cliente-create' opcion=0%}">Registrar Cliente</a>
            </div>
            <!-- <form method="post" novalidate> -->
            <form method="post">
                {% csrf_token %}
                {% crispy form form.helper %}
                <!-- <div class="botones_form">
                    <button type="submit" class="btn btn-dark">Registrar Evento</button>
                </div> -->
            </form>
        </div>
{% endblock %}

alquileres_eventos/templates/alquileres_eventos/eventos_list.html
{% extends 'alquileres_eventos/base.html' %}

{% load static %}

{% block content %}

    <style>

        .el_medio2{
            display: flex;
            /* flex-flow: row wrap;
            align-items: stretch; */
            height: 100vh;
            width: 70vw;
            padding-left: 5vw;
            padding-right: 5vw;
            background: linear-gradient(180deg, rgba(242, 98, 36, 0.0847259) 0%, rgba(242, 36, 36, 0.14827) 51.04%, rgba(242, 98, 36, 0.14827) 98.44%, rgba(242, 36, 36, 0.14827) 98.45%);
            border-radius: 8px;
            /* flex-shrink: 1; */
            position: relative;
            text-align: center;
        }

        .botones{
            display: flex;
            align-items:center;
            justify-content:center;
            align-items:flex-end;

            position: absolute;
            bottom: 0;
            left: 0;
            right: 0;
        }

        .boton_bordo{
        background: linear-gradient(180deg, rgba(228, 22, 22, 0.849) 0%, rgba(197, 21, 12, 0.555) 52.08%, rgba(228, 22, 22, 0.849) 100%);
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.25);
        border-radius: 11px;
        }

      h4{
        color: #5B0101;
        align-self: center;
        margin-top: 20px;
        margin-bottom: 20px;
        position: relative;
      }
      .container{
      background: linear-gradient(180deg, rgba(242, 98, 36, 0.0847259) 0%, rgba(242, 36, 36, 0.14827) 51.04%, rgba(242, 98, 36, 0.14827) 98.44%, rgba(242, 36, 36, 0.14827) 98.45%);
      height: 100vh;
      text-align: center;
    }
    </style>


  <!-- <div class="container"> -->
    <div class="container">
      <h4>Eventos</h4>
    <table class="table table-bordered  table-striped table-hover">
        <thead>
          <tr>
            <th colspan="2"></th>
            <th colspan="2">Inicio</th>
            <th colspan="2">Fin</th>
          </tr>
          <tr>
            <th width="20%">Nombre</th>
            <th width="15%">Cliente</th>
            <th width="15%">Fecha</th>
            <th width="10%">Hora</th>
            <th width="15%">Fecha</th>
            <th width="10%">Hora</th>
            <th width="15%">Acciones</th>
          </tr>
        </thead>
        <tbody>
        
        <!-- Recorremos los objetos o registros que tenemos en nuestra tabla 'postres' y los listamos -->
        {% for evento in object_list %}
          <tr style="border-top: 1px solid rgba(29, 28, 28, 0.3); 
          border-bottom: 1px solid rgba(29, 28, 28, 0.3); ">
            <td>{{ evento.nombre }}</td>
            <td>{{ evento.cliente }}</td>
            <td>{{ evento.fecha_inicio }}</td>
            <td>{{ evento.horario_inicio }}</td>
            <td>{{ evento.fecha_fin }}</td>
            <td>{{ evento.horario_fin }}</td>
            <td>
       
              <!-- Usaremos un formulario que realizará la tarea de eliminar un registro o postre desde la misma tabla HTML -->                        
              <form method="POST" action="{% url 'alquileres_eventos:evento-eliminar' pk=evento.id%}">
                {% csrf_token %}
                <div class="btn-group">
       
                  <!-- Creamos 3 botones que son ver, Editar y Eliminar, nos sirven para gestionar nuestros registros o postres -->
                  <a href="{% url 'alquileres_eventos:evento-detalle' pk=evento.id%}" title="Ver" type="button" class="btn btn-dark">Ver </a>
                  <a href="{% url 'alquileres_eventos:evento-editar' pk=evento.id%}" title="Editar" type="button" class="btn btn-dark">Editar </a>
                  <!-- <button class="btn btn-danger" onclick="return eliminar();" type="submit"> -->
                    <button class="btn btn-danger" onclick="return eliminar();" type="submit">
                        Eliminar
                  </button>
                </div>
              </form>
       
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>

    <div class="row botones" style="position:relative;">
      <a class="btn btn-dark boton_bordo" id="btn-crear" href="{% url 'alquileres_eventos:evento-create' cedula=0 %}">Agregar Evento</a>
    </div>

  </div>
  <script type="text/javascript">
    function eliminar() {
      var x = confirm("Eliminar Evento ?");
      if (x)
        return true;
      else
        return false;
    }
  </script>

{% endblock %}

alquileres_eventos/templates/alquileres_eventos/sectores_list.html
{% extends 'alquileres_eventos/base.html' %}

{% block content %}

    <style>

      .el_medio2{
            display: flex;
            /* flex-flow: row wrap;
            align-items: stretch; */
            height: 100vh;
            width: 70vw;
            padding-left: 5vw;
            padding-right: 5vw;
            background: linear-gradient(180deg, rgba(242, 98, 36, 0.0847259) 0%, rgba(242, 36, 36, 0.14827) 51.04%, rgba(242, 98, 36, 0.14827) 98.44%, rgba(242, 36, 36, 0.14827) 98.45%);
            border-radius: 8px;
            /* flex-shrink: 1; */
            position: relative;
            text-align: center;
        }

        .botones{
            display: flex;
            align-items:center;
            justify-content:center;
            align-items:flex-end;

            position: absolute;
            bottom: 0;
            left: 0;
            right: 0;
        }
        .boton_bordo{
        background: linear-gradient(180deg, rgba(228, 22, 22, 0.849) 0%, rgba(197, 21, 12, 0.555) 52.08%, rgba(228, 22, 22, 0.849) 100%);
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.25);
        border-radius: 11px;
        }

      h4{
        color: #5B0101;
        align-self: center;
        margin-top: 20px;
        margin-bottom: 20px;
      }
      .container{
      background: linear-gradient(180deg, rgba(242, 98, 36, 0.0847259) 0%, rgba(242, 36, 36, 0.14827) 51.04%, rgba(242, 98, 36, 0.14827) 98.44%, rgba(242, 36, 36, 0.14827) 98.45%);
      height: 100vh;
      text-align: center;
    }

    </style>


  <!-- <div class="container"> -->
    <div class="container">
      <h4>Sectores</h4>
    <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th width="35%">Nombre</th>
            <th>Precio sin Membresia</th>
            <!-- <th>Stock</th>
            <th>Imagen</th> -->
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
        
        <!-- Recorremos los objetos o registros que tenemos en nuestra tabla 'postres' y los listamos -->
        {% for sector in object_list %}
          <tr style="border-top: 1px solid rgba(29, 28, 28, 0.3); 
          border-bottom: 1px solid rgba(29, 28, 28, 0.3); ">
            <td>{{ sector.nombre }}</td>
            <td>{{ sector.precion_normal }}</td>
            <td>
       
              <!-- Usaremos un formulario que realizará la tarea de eliminar un registro o postre desde la misma tabla HTML -->                        
              <form method="POST" action="{% url 'alquileres_eventos:sector-eliminar' pk=sector.id%}">
                {% csrf_token %}
                <div class="btn-group">
       
                  <!-- Creamos 3 botones que son ver, Editar y Eliminar, nos sirven para gestionar nuestros registros o postres -->
                  <a href="{% url 'alquileres_eventos:sector-detalle' pk=sector.id%}" title="Ver" type="button" class="btn btn-dark">Ver </a>
                  <a href="{% url 'alquileres_eventos:sector-editar' pk=sector.id%}" title="Editar" type="button" class="btn btn-dark">Editar </a>
                  <button class="btn btn-danger" onclick="return eliminar();" type="submit">
                    Eliminar
                  </button>
                </div>
              </form>
       
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>

      <div class="row botones" style="position: relative;">
        <a class="btn btn-dark boton_bordo"  id="btn-crear" href="{% url 'alquileres_eventos:sector-create' %}">Crear Sector</a>
    </div>

  </div>
  <script type="text/javascript">
    function eliminar() {
      var x = confirm("Eliminar Sector ?");
      if (x)
        return true;
      else
        return false;
    }
  </script>

{% endblock %}

alquileres_eventos/templates/alquileres_eventos/servicios_list.html
{% extends 'alquileres_eventos/base.html' %}

{% block content %}

<style>

  .el_medio2{
      display: flex;
      /* flex-flow: row wrap;
      align-items: stretch; */
      height: 100vh;
      width: 70vw;
      padding-left: 5vw;
      padding-right: 5vw;
      background: linear-gradient(180deg, rgba(242, 98, 36, 0.0847259) 0%, rgba(242, 36, 36, 0.14827) 51.04%, rgba(242, 98, 36, 0.14827) 98.44%, rgba(242, 36, 36, 0.14827) 98.45%);
      border-radius: 8px;
      /* flex-shrink: 1; */
      position: relative;
      text-align: center;
  }

  .botones{
      display: flex;
      align-items:center;
      justify-content:center;
      align-items:flex-end;

      position: absolute;
      bottom: 0;
      left: 0;
      right: 0;
  }
  .boton_bordo{
  background: linear-gradient(180deg, rgba(228, 22, 22, 0.849) 0%, rgba(197, 21, 12, 0.555) 52.08%, rgba(228, 22, 22, 0.849) 100%);
  box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.25);
  border-radius: 11px;
  }

  h4{
        color: #5B0101;
        align-self: center;
        margin-top: 20px;
        margin-bottom: 20px;
    }
    .container{
      background: linear-gradient(180deg, rgba(242, 98, 36, 0.0847259) 0%, rgba(242, 36, 36, 0.14827) 51.04%, rgba(242, 98, 36, 0.14827) 98.44%, rgba(242, 36, 36, 0.14827) 98.45%);
      height: 100vh;
      text-align: center;
    }
</style>

  <!-- <div class="container"> -->
    <div class="container">
      <h4>Servicios</h4>
    <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th width="35%">Nombre</th>
            <th>Precio sin Membresia</th>
            <!-- <th>Stock</th>
            <th>Imagen</th> -->
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
        
        <!-- Recorremos los objetos o registros que tenemos en nuestra tabla 'postres' y los listamos -->
        {% for servicio in object_list %}
          <tr style="border-top: 1px solid rgba(29, 28, 28, 0.3); 
          border-bottom: 1px solid rgba(29, 28, 28, 0.3); ">
            <td>{{ servicio.nombre }}</td>
            <td>{{ servicio.precion_normal }}</td>
            <td>
       
              <!-- Usaremos un formulario que realizará la tarea de eliminar un registro o postre desde la misma tabla HTML -->                        
              <form method="POST" action="{% url 'alquileres_eventos:servicio-eliminar' pk=servicio.id%}">
                {% csrf_token %}
                <div class="btn-group">
                  <!-- Creamos 3 botones que son ver, Editar y Eliminar, nos sirven para gestionar nuestros registros o postres -->
                  <a href="{% url 'alquileres_eventos:servicio-detalle' pk=servicio.id%}" title="Ver" type="button" class="btn btn-dark">Ver </a>
                  <a href="{% url 'alquileres_eventos:servicio-editar' pk=servicio.id%}" title="Editar" type="button" class="btn btn-dark">Editar </a>
                  <button class="btn btn-danger" onclick="return eliminar();" type="submit">
                    Eliminar
                  </button>
                </div>
              </form>
       
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>

      <div class="row botones" style="position: relative;">
        <a class="btn btn-dark boton_bordo" id="btn-crear" href="{% url 'alquileres_eventos:servicio-create' %}">Crear Servicio</a>
      </div>
  </div>
  <script type="text/javascript">
    function eliminar() {
      var x = confirm("Eliminar Servicio ?");
      if (x)
        return true;
      else
        return false;
    }
  </script>

{% endblock %}