Riverside/urls.py
from django.contrib import admin
from django.urls import path, include
from alquileres_eventos import views as alquileres_eventos_views
from users import views as users_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('alquileresyeventos/',include('alquileres_eventos.urls')),
    path('clientesysocios/',include('clientes_socios.urls')),
    path('users/', include('users.urls')),

    path('',alquileres_eventos_views.home, name='home'),
    path('register', users_views.registrar_usuario,name='register'),
    path('login', users_views.login_usuario, name= 'login'),
    path('logout', users_views.salir, name='logout'),
]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from .views import *

app_name='users'

urlpatterns = [
    path('usuarios/', UserListView.as_view(template_name="users/user_list.html"), name='user-lista'),

    # path('lista_roles/',ListarRoles.as_view(template_name="users/roles_list.html"),name="roles-lista"),
    # path('crear_rol/', CrearRol.as_view(template_name="users/rol_form.html"),name="rol-crear"),
    # path('detalle_rol/<int:pk>', RolDetalle.as_view(template_name="users/rol_detalle.html"),name="rol-detalle"),
    # path('actualizar_rol/<int:pk>', RolActualizar.as_view(template_name="users/rol_editar.html"),name="rol-editar"),
    # path('eliminar_rol/<int:pk>', RolEliminar.as_view(),name="rol-eliminar"),

    
    path('<int:pk>/', UserDetailView.as_view(template_name="users/user_detail.html"), name='user-detalle'),
    path('<int:pk>/update', UserUpdateView.as_view(template_name="users/user_update.html"), name='user-editar'),
    path('eliminar_usuarios/<int:pk>', UserEliminar.as_view(),name="user-eliminar"),
    # path('<int:pk>/roles', RolUpdateView.as_view(template_name="users/anadir_rol.html"),
    # name="anadir-rol"),
    path('habilitar/<int:pk>/<int:opcion>/', views.habilitarVista, name="habilitar-staff"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User, Permission, Group

# class Rol(models.Model):

#         nombre = models.CharField(max_length=50)
#         descripcion = models.CharField(max_length=100, null=True, blank=True)
#         permisos = models.ManyToManyField(Permission)


class Perfil(models.Model):

	ESTADOS =(
			('Activo', 'Activo'),
			('Inactivo','Inactivo'),
			)

	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
	celular = models.CharField(max_length=12, null=True)
	email = models.CharField(max_length=30, null=True)
	direccion = models.CharField(max_length=100, null=True)
	fecha_nac = models.DateField(max_length=50, null=True)
	estado = models.CharField(max_length=50, null=True, choices=ESTADOS, default=ESTADOS[0][0])
	verificado = models.BooleanField(default=False)
	es_gerente = models.BooleanField(default=False)

	def __str__(self):
		return f'{ self.user.username }'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from users.widgets import *
from users.models import *

# Extendemos del original
class  RegistroEmail(UserCreationForm):
    # Ahora el campo username es de tipo email y cambiamos su texto
    nombre = forms.CharField(max_length=12)
    apellido = forms.CharField(max_length=12)
    celular = forms.CharField(max_length=12)
    direccion = forms.CharField(max_length=30)
    # fecha_nacimiento = forms.DateTimeField(
    #     input_formats=['%d/%m/%Y'], 
    #     widget=BootstrapDateTimePickerInput()
    # )
    fecha_nacimiento = forms.DateTimeField(
        input_formats=['%d/%m/%Y'], 
        widget=CalendarioInput()
    )

    class Meta:
        model = User
        fields = ["username", "nombre", "apellido", "email", "password1", "password2", "celular", "direccion", "fecha_nacimiento"]


# Extendemos del original
class LoginEmail(AuthenticationForm):
    # Ahora el campo username es de tipo email y cambiamos su texto
    # username = forms.EmailField(label="Correo electrónico")

    class Meta:
        model = User
        fields = ["username", "password"]

# class AnadirRolForm(forms.ModelForm):
#     def __init__(self, *args, **kwargs):
#         super(AnadirRolForm, self).__init__(*args, **kwargs)
#         self.fields['roles'].queryset =  Rol.objects.filter(es_desistema=True)

#     class Meta:
#         model= Perfil
#         fields= ['roles']
#         widgets = {
#         'roles' : forms.CheckboxSelectMultiple()}

users/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from guardian.mixins import PermissionRequiredMixin, PermissionListMixin
from django.http import HttpResponse, HttpResponseRedirect
from .forms import *
from .models import *


def registrar_usuario(request, backend='django.contrib.auth.backends.ModelBackend'):

    form = RegistroEmail()

    if request.method == "POST":
        form = RegistroEmail(data=request.POST)
        # Si el formulario es válido...
        if form.is_valid():

            # Creamos la nueva cuenta de usuario
            user = form.save()

            nombre = form.cleaned_data['nombre']
            apellido = form.cleaned_data['apellido']
            celular = form.cleaned_data['celular']
            direccion = form.cleaned_data['direccion']
            nacimiento = form.cleaned_data['fecha_nacimiento']
            email = form.cleaned_data['email']

            user.first_name = nombre
            user.last_name = apellido
            user.is_active = True
            user.save()
            Perfil.objects.create(user=user, celular=celular, direccion=direccion, fecha_nac=nacimiento, email=email)
            # Si el usuario se crea correctamente 
            # if user is not None:
            #     # Hacemos el login manualmente
            #     login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            #     # Y le redireccionamos a la portada
            #     return redirect('/')

    # Si llegamos al final renderizamos el formulario
    # return render(request, 'acceso/register.html', {'form_user': form_user, 'form_perfil': form_perfil})
    return render(request, 'users/registrar_usuario.html', {'form': form})

def login_usuario(request):
    # Creamos el formulario de autenticación vacío
    form = LoginEmail()
    if request.method == "POST":
        # Añadimos los datos recibidos al formulario
        form = LoginEmail(data=request.POST)
        # Si el formulario es válido...
        if form.is_valid():
            # Recuperamos las credenciales validadas
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            # Verificamos las credenciales del usuario
            user = authenticate(username=username, password=password)

            # Si existe un usuario con ese nombre y contraseña
            if user is not None:
                # Hacemos el login manualmente
                login(request, user)
                # Y le redireccionamos a la portada
                return redirect('/')

    # Si llegamos al final renderizamos el formulario
    return render(request, "users/login.html", {'form': form})


def salir(request):
    # Finalizamos la sesión
    logout(request)
    # Redireccionamos a la portada
    return redirect('/')

# class ListarRoles(ListView):

#     model = Rol

# class CrearRol(SuccessMessageMixin,CreateView):
#     model = Rol
#     # form = ServicioCreateForm
#     fields = '__all__'
#     success_message = 'Rol Creado Correctamente !' # Mostramos este Mensaje luego de Crear un Departamento

#     # Redireccionamos a la vista con la lista de Departamentos
#     def get_success_url(self):        
#         return reverse('users:roles-list')

# class RolDetalle(DetailView): 
#     model = Rol

# class RolActualizar(SuccessMessageMixin, UpdateView): 
#     model = Rol
#     form = Rol
#     fields = '__all__'
#     success_message = 'Rol Actualizada Correctamente !'
 
#     def get_success_url(self):               
#         # return reverse('alquileres_eventos:servicio-detalle')
#         return reverse('users:roles-list')

# class RolEliminar(SuccessMessageMixin, DeleteView): 
#     model = Rol 
#     form = Rol
#     fields = "__all__"     
 
#     # Redireccionamos a la página principal luego de eliminar un registro o postre
#     def get_success_url(self): 
#         success_message = 'Rol Eliminado Correctamente !'
#         messages.success (self.request, (success_message))       
#         return reverse('users:roles-list')

class UserListView(LoginRequiredMixin, ListView):
    """
    Vista de lista de usuarios
    """
    login_url = ''
    template_name = "users/user_list.html"
    model = User
    
    def get_queryset(self):
        """
        Se muestra el usuario que se recibio
        por el form haciendo un get del query a los
        objetos users
        """
        query = self.request.GET.get('username')
        
        if query:
            object_list = self.model.objects.filter(username__icontains=query)
            if object_list.count() == 0:
                messages.error(self.request, 'Usuario no encontrado')
        else:
            object_list = self.model.objects.all()
        
        return object_list.order_by('username')


# class RolUpdateView(UpdateView):
#     """
#     Añade un rol general de sistema a un usuario en especifico
#     """
#     form_class= AnadirRolForm
#     model = Perfil
#     template_name = 'users/anadir_rol.html'
#     #queryset = Rol.objects.all()
#     #permission_required = ['view_rol']

#     def get_object(self):
#         id_ = self.kwargs.get("id")
#         return get_object_or_404(Perfil, id=id_)

#     #def get_initial(self, *args, **kwargs):
#     #    initial = super(RolUpdateView, self).get_initial(**kwargs)
#     #    initial['roles'] =  Rol.objects.all()
#     #    return initial

#     def get_context_data(self, **kwargs):
#         contexto = super(RolUpdateView, self).get_context_data(**kwargs)
#         #contexto['roles'] = get_object_or_404(Rol, id=self.kwargs['id'])
#         #contexto['usuario'] = get_object_or_404(User, id=self.kwargs['id'])
#         return contexto

#     def form_valid(self,form):
#          self.object = form.save(commit = False)
#          roles_=form.cleaned_data.get('roles')
#          self.object.roles.set(roles_)
#          for rol in roles_.all():
#              for permiso in rol.permisos.all():
#                  self.object.user.user_permissions.add(permiso)
#          #self.object.roles = self.request.POST.getlist('roles')
#          #print(request.POST.get('roles'))
#          self.object.save()
#          return super(RolUpdateView, self).form_valid(form)

def habilitarVista(request,pk,opcion=None):
    """
    Añade o quita el permiso de ver sitios a los usuarios, y tambien su condicion de staff del sistema
    param id: Es el id al que se le va a añadir o quitar permisos
    param opcion: Igual a 1 si se le va a dar el permiso de ver sitios y hacerle staff del sistema
    param opcion: Igual a 2 si se le va a quitar el permiso de ver sitios y quitarle la condicion de staff del sistema
    """
    if request.method=='POST':
        context={
        }
        estado=False
        usuario=User.objects.get(id=pk)
        print("El usuario recibido es: ",usuario)
        verSitio_perm=Permission.objects.get(codename='view_site')
        if(opcion==1):
            usuario.user_permissions.add(verSitio_perm)
            usuario.is_staff=True
        else:
            usuario.user_permissions.remove(verSitio_perm)
            usuario.is_staff=False
        usuario.save()
        estado=False
        context={        
                "estado":estado
        }
        return render(request,'user-lista',context)
        # return HttpResponseRedirect(reverse('users:user-lista'))


class UserDetailView(LoginRequiredMixin, DetailView):
    """
    Vista de detalles de Usuario
    """
    login_url = ''
    template_name = 'user_detail'

    def get_object(self):
        id_ = self.kwargs.get("pk")
        return get_object_or_404(User, id=id_)

class UserUpdateView(LoginRequiredMixin, UpdateView):
    """
    Vista de actualizacion del perfil
    """
    template_name = 'users/user_update.html'
    fields = ['direccion','fecha_nac','celular','email']

    def get_object(self):
        """
        Retorna el objecto a usarse, en este caso
        el perfil del usuario
        """
        user = get_object_or_404(User, id=self.kwargs['pk'])
        return user.perfil

class UserEliminar(SuccessMessageMixin, DeleteView): 
    model = User 
    form = User
    fields = "__all__"     
 
    # Redireccionamos a la página principal luego de eliminar un registro o postre
    def get_success_url(self): 
        success_message = 'Usuario Eliminado Correctamente !'
        messages.success (self.request, (success_message))       
        return reverse('users:user-lista')

users/templates/users/anadir_rol.html
{% extends 'alquileres_eventos/base.html' %}

{% block content %}
    <div class="container">
        <form method="post" novalidate>
            {% csrf_token %}
            {% include 'alquileres_eventos/forms_b4.html' with form=form %}
            <div class="botones_form">
                <button type="submit" class="btn btn-dark">Aceptar</button>
            </div>
          </form>
    </div>
{% endblock %}


<!-- {% block content %}

    <form method = "POST" action = "">
        {% csrf_token %}
        <p>Roles: {{form.roles}}</p> -->
    <!--    {% for rol in roles.all %}
            <input type="radio" name="rol" id="rol{{ forloop.counter }}" value="{{ rol.nombre }}">
            <label for="rol{{ forloop.counter }}">{{ rol.nombre }}</label><br>
        {% endfor %}
    --> 
        <!-- <input  type = "submit" value="Update">
    </form>


{% endblock %} -->

users/templates/users/bootstrap_datetimepicker.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Static Example</title>

    <!-- Bootstrap 4 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    <!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>

  </head>
  <body>

    <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
      <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker1"/>
      <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
      </div>
    </div>

    <script>
      $(function () {
        $("#datetimepicker1").datetimepicker();
      });
    </script>

  </body>
</html>

users/templates/users/calendario_datetimepicker.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Static Example</title>
  <style>body {font-family: Arial, sans-serif;}</style>
  
  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <!-- Fengyuan Chen's Datepicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
</head>
<body>
  
  {% include "django/forms/widgets/input.html" %}

  <script>
    $(function () {
      $("input[name='{{ widget.name }}']").datepicker({
        format:'dd/mm/yyyy',
      });
    });
  </script>

</body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="favicon.ico">
     
        <title>Riverside</title>

        {% load static %}

        <link rel="stylesheet" href="{% static 'css/general.css' %}">
     
        {# Cargamos la librería #}
        {% load bootstrap4 %}

        {# CSS Bootstrap #}
        {% bootstrap_css %}



        <!-- <style>

        </style> -->
 
    </head>
    <body>
        {% block content %}
            <div class="container">
                <h2>Iniciar sesión</h2>
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% include 'alquileres_eventos/forms_b4.html' with form=form %}
                    <div class="botones_form">
                        <button type="submit" class="btn btn-dark">Login</button>
                    </div>
                </form>
            </div>
            <hr />
        {% endblock %}

        {% bootstrap_javascript jquery='full' %}
    </body>
</html>

users/templates/users/registrar_usuario.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="favicon.ico">
     
        <title>Riverside</title>

        {% load static %}

        <link rel="stylesheet" href="{% static 'css/general.css' %}">
     
        {# Cargamos la librería #}
        {% load bootstrap4 %}

        {# CSS Bootstrap #}
        {% bootstrap_css %}



        <!-- <style>

        </style> -->
 
    </head>
        {% block content %}
            <h2>Registrar Usuario</h2>
            <div class="container">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% include 'alquileres_eventos/forms_b4.html' with form=form %}
                    <div class="botones_form">
                        <button type="submit" class="btn btn-dark">Registrar</button>
                    </div>
                </form>
            </div>
            <hr />
            <a href="{% url 'login' %}">Iniciar Sesion</a>

            <script>
                $('#id_fecha_nacimiento').datepicker({autoHide: 'True',endDate:'True', format: 'dd/mm/yyyy', iconsLibrary: 'fontawesome', width: 276, modal: true, footer: true, uiLibrary: 'bootstrap4'});
            </script>
            
            <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
            
        {% endblock %}

        
        {% bootstrap_javascript jquery='full' %}
    </body>
</html>

users/templates/users/rol_detalle.html
{% extends 'alquileres_eventos/base.html' %}

{% block content %}


<div class="container" style="text-align: center; padding-top: 1%;">
  <h2>Rol de {{ object.nombre }}</h2>
  <h2>Permisos</h2>
  {% for permiso in object.permisos.all %}
  <ul class="nav nav-tabs">
    <li class="nav-item">
        {{ permiso }}
    </li>
  </ul>
  {% endfor %}

{% endblock %}

users/templates/users/user_detail.html
{% extends 'alquileres_eventos/base.html' %}

{#% block content %#}
<!-- <div class="card border-dark mb-3 mt-4">
    <div class="card-header text-center">
        <h4>Detalles del Usuario</h4>
    </div>
    <div class="contenedor ">
        <div class="row border ml-auto mr-auto">
            <div class="col-sm pt-4 border-right-1">
                <h5 class="card-title text-center"><u>General</u></h5>
                <div class="card-text">
                    <p>Usuario: {{ object.username }}</p>
                    <p>Nombre: {{ object.first_name }}</p>
                    <p>Apellido: {{ object.last_name }}</p>
                    <p>email: {{ object.email }}</p>
                    <p>Direccion: {{ object.perfil.direccion }}</p>
                    <p>Fecha de nacimiento: {{ object.perfil.fecha_nac }}</p>
                    <hr>
                    <p>Ultima conexion: {{ object.last_login }}</p>
                    <p>Fecha de Registro: {{ object.date_joined }}</p>
                    <p>Estado: {{ object.perfil.estado }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="contenedor row justify-content-center mt-5">
    {% if request.user.is_superuser %}
    <a class="btn btn-dark" href="{% url 'anadir-rol' id=object.perfil.id %}">Añadir Rol</a>
    {%endif%}
    {% if request.user.id == object.id %}
        <a class="btn btn-dark" href="{% url 'users:user-editar' pk=object.id %}">Modificar</a>
    {% endif %}
</div> -->

{#% endblock %#}

{% block content %}
<div class="card text-center">
    <div class="card-header">
        <h5 class="card-title">Informacion del Usuario: {{ object.username }}</h5>
    </div>
    <div class="card-body">
        <p class="card-text">Nombre: {{ object.first_name }}</p>
        <p class="card-text">Apellido: {{ object.last_name }}</p>
        <p class="card-text">email: {{ object.email }}</p>
        <p class="card-text">Direccion: {{ object.perfil.direccion }}</p>
        <p class="card-text">Fecha de nacimiento: {{ object.perfil.fecha_nac }}</p>
        <hr>
        <p>Ultima conexion: {{ object.last_login }}</p>
        <p>Fecha de Registro: {{ object.date_joined }}</p>
        <p>Estado: {{ object.perfil.estado }}</p>
    </div>
    <div class="card-footer text-muted">
        <div class="contenedor row justify-content-center mt-5">
            {% if request.user.is_superuser %}
            <a class="btn btn-dark" href="{% url 'anadir-rol' id=object.perfil.id %}">Añadir Rol</a>
            {%endif%}
            {% if request.user.id == object.id %}
                <a class="btn btn-dark" href="{% url 'users:user-editar' pk=object.id %}">Modificar</a>
            {% endif %}
        </div>
    </div>
  </div>
  {% endblock %}

users/templates/users/user_list.html
{% extends 'alquileres_eventos/base.html' %}

{% block content %}
<!--------------------- ESTILOS --------------------->
<style>
    
    .col-lg-1 {
        margin-top: 10px;
    }
    .item-user{
        color: #343A40;
    }
    .item-user:hover{
        color: rgb(105, 105, 105);
    }
    h4{
        color: #5B0101;
        align-self: center;
        margin-top: 20px;
        margin-bottom: 20px;
    }
    .list-group-item{
        background-color: transparent;
        border-top: 1px solid rgba(29, 28, 28, 0.3); 
        border-bottom: 1px solid rgba(29, 28, 28, 0.3);
    }
    .boton_bordo{
        background: linear-gradient(180deg, rgba(228, 22, 22, 0.849) 0%, rgba(197, 21, 12, 0.555) 52.08%, rgba(228, 22, 22, 0.849) 100%);
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.25);
        border-radius: 11px;
    }

    .el_medio2{
    display: flex;
    /* flex-flow: row wrap;
    align-items: stretch; */
    height: 100vh;
    width: 70vw;
    padding-left: 5vw;
    padding-right: 5vw;
    background: linear-gradient(180deg, rgba(242, 98, 36, 0.0847259) 0%, rgba(242, 36, 36, 0.14827) 51.04%, rgba(242, 98, 36, 0.14827) 98.44%, rgba(242, 36, 36, 0.14827) 98.45%);
    border-radius: 8px;
    /* flex-shrink: 1; */
    position: relative;
    text-align: center;
    }
    .container{
      background: linear-gradient(180deg, rgba(242, 98, 36, 0.0847259) 0%, rgba(242, 36, 36, 0.14827) 51.04%, rgba(242, 98, 36, 0.14827) 98.44%, rgba(242, 36, 36, 0.14827) 98.45%);
      height: 100vh;
      text-align: center;
    }
</style>
<!--------------------- FIN ESTILOS --------------------->

<div class="container">
<h4>Usuarios</h4>

<ol class="list-group list-group-flush">
    {% for instance in object_list %}
    <ul class="list-group list-group-horizontal col-10 offset-2">
        <li class="list-group-item col-5">
            <a class="item-user" href="{{ instance.id }}">{{ instance.username }}</a>
        </li>
        <li class="list-group-item col-5">
            <form method="POST" action="{% url 'users:user-eliminar' pk=instance.id%}">
                {% csrf_token %}
                <div class="btn-group">
       
                  <!-- Creamos 3 botones que son ver, Editar y Eliminar, nos sirven para gestionar nuestros registros o postres -->
                  <a href="{% url 'users:user-detalle' pk=instance.id%}" title="Ver" type="button" class="btn btn-dark">Ver </a>
                  <a href="{% url 'users:user-editar' pk=instance.id%}" title="Editar" type="button" class="btn btn-dark">Editar </a>
                  <button class="btn btn-danger" onclick="return eliminar();" type="submit">
                    Eliminar
                  </button>
                </div>
            </form>
        </li>
      </ul>
    {% endfor %} 
</ol>
<div class="row justify-content-center" style="margin-top: 20px; position: relative;">
    <div class="col-4">
        <a class="btn btn-dark boton_bordo" href="{% url 'register' %}">Registrar nuevo usuario</a>
    </div>
</div>
</div>

{% endblock %}