Riverside/urls.py
from django.contrib import admin
from django.urls import path, include
from alquileres_eventos import views as alquileres_eventos_views
from users import views as users_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('alquileresyeventos/',include('alquileres_eventos.urls')),
    path('clientesysocios/',include('clientes_socios.urls')),
    path('users/', include('users.urls')),

    path('',alquileres_eventos_views.home, name='home'),
    path('register', users_views.registrar_usuario,name='register'),
    path('login', users_views.login_usuario, name= 'login'),
    path('logout', users_views.salir, name='logout'),
]

clientes_socios/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from .views import *

app_name='clientes_socios'

urlpatterns = [
    path('membresias/',ListarMembresias.as_view(template_name="clientes_socios/membresias_list.html"),name="membresias-list"),
    path('crear_membresia/', CrearMembresia.as_view(template_name="clientes_socios/membresia_form.html"),name="membresia-create"),
    path('detalle_membresia/<int:pk>', MembresiaDetalle.as_view(template_name="clientes_socios/membresia_detalle.html"),name="membresia-detalle"),
    path('actualizar_membresia/<int:pk>', MembresiaActualizar.as_view(template_name="clientes_socios/membresia_editar.html"),name="membresia-editar"),
    path('eliminar_membresia/<int:pk>', MembresiaEliminar.as_view(),name="membresia-eliminar"),

    path('socios/',ListarSocios.as_view(template_name="clientes_socios/socios_list.html"),name="socios-list"),
    path('crear_socio/<int:cedula>', CrearSocio.as_view(template_name="clientes_socios/socio_form.html"),name="socio-create"),
    path('detalle_socio/<int:pk>', SocioDetalle.as_view(template_name="clientes_socios/socio_detalle.html"),name="socio-detalle"),
    path('actualizar_socio/<int:pk>', SocioActualizar.as_view(template_name="clientes_socios/socio_editar.html"),name="socio-editar"),
    path('eliminar_socio/<int:pk>', SocioEliminar.as_view(),name="socio-eliminar"),

    path('registrar_cliente/<int:opcion>', RegistrarCliente.as_view(template_name="clientes_socios/cliente_form.html"),name="cliente-create"),
]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from .views import *

app_name='users'

urlpatterns = [
    path('usuarios/', UserListView.as_view(template_name="users/user_list.html"), name='user-lista'),

    # path('lista_roles/',ListarRoles.as_view(template_name="users/roles_list.html"),name="roles-lista"),
    # path('crear_rol/', CrearRol.as_view(template_name="users/rol_form.html"),name="rol-crear"),
    # path('detalle_rol/<int:pk>', RolDetalle.as_view(template_name="users/rol_detalle.html"),name="rol-detalle"),
    # path('actualizar_rol/<int:pk>', RolActualizar.as_view(template_name="users/rol_editar.html"),name="rol-editar"),
    # path('eliminar_rol/<int:pk>', RolEliminar.as_view(),name="rol-eliminar"),

    
    path('<int:pk>/', UserDetailView.as_view(template_name="users/user_detail.html"), name='user-detalle'),
    path('<int:pk>/update', UserUpdateView.as_view(template_name="users/user_update.html"), name='user-editar'),
    path('eliminar_usuarios/<int:pk>', UserEliminar.as_view(),name="user-eliminar"),
    # path('<int:pk>/roles', RolUpdateView.as_view(template_name="users/anadir_rol.html"),
    # name="anadir-rol"),
    path('habilitar/<int:pk>/<int:opcion>/', views.habilitarVista, name="habilitar-staff"),
]

clientes_socios/models.py
from django.db import models

# Create your models here.
class Cliente(models.Model):

    cedula = models.BigIntegerField()
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    celular = models.CharField(max_length=12, null=True)
    email = models.CharField(max_length=30, blank=True, null=True)
    direccion = models.CharField(max_length=100, null=True)
    fecha_nac = models.DateField(max_length=50, null=True)

    def __str__(self):
        return f' {self.nombre}'

class Membresia(models.Model):

    nombre = models.CharField(max_length=30)
    descripcion = models.CharField(max_length=100, null=True)
    precio_anual = models.DecimalField(decimal_places=2, max_digits=12, help_text="Precio de la membresia")

    def __str__(self):
        return f' {self.nombre}'

class Socio(models.Model):

    cliente = models.OneToOneField(Cliente,on_delete=models.DO_NOTHING)
    membresia = models.ForeignKey(Membresia,on_delete=models.DO_NOTHING)
    fecha_renovacion = models.DateField()

    def __unicode__(self):
        return self.date

clientes_socios/forms.py
from django import forms
from django.contrib.auth.models import User, Permission
from django.forms.widgets import CheckboxSelectMultiple
from datetime import datetime, time, date, timedelta
from datetime import timedelta
from dateutil.relativedelta import relativedelta
from django.conf import settings
from .models import *
from users.widgets import *

class MembresiaCreateForm(forms.ModelForm):

    class Meta:
        model = Membresia
        fields = '__all__'


class SocioCreateForm(forms.ModelForm):

    cedula = forms.CharField( widget=forms.TextInput(attrs={'size': '9'}), help_text="Ingrese la cedula del cliente")
    fecha_renovacion= forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)

    class Meta:
        model = Socio
        fields = ['cedula','membresia','fecha_renovacion']

    def __init__(self, cliente, *args, **kwargs):
        super(SocioCreateForm, self).__init__(*args, **kwargs)
        self.ced = cliente
        if self.ced != 0:
            self.fields['cedula'].initial=self.ced
        ahora = date.today()
        tiempo = time(0, 0)
        renovacion = ahora + relativedelta(years=1)
        renovacion = ahora + timedelta(days=365 )
        self.fields['fecha_renovacion'].initial  = datetime.combine(renovacion, tiempo).strftime('%d/%m/%Y')

    def clean_cedula(self):
        cedula = self.cleaned_data.get("cedula")

        if cedula.isdigit():
            resultado = Cliente.objects.filter(cedula=cedula).count()
            if resultado == 0:
                raise forms.ValidationError("La cedula ingresada no existe en la base de datos")
            else:
                resultado2 = Socio.objects.filter(cliente__cedula=cedula).count()
                if resultado2 == 0:
                    raise forms.ValidationError("Ya existe un socio registrado con esta cedula")
                else:
                    cliente = Cliente.objects.filter(cedula=cedula)
        else:
            raise forms.ValidationError("La cedula solamente puede contener numeros!")

class ClienteCreateForm(forms.ModelForm):

    # Ahora el campo username es de tipo email y cambiamos su texto
    nombre = forms.CharField(max_length=15)
    apellido = forms.CharField(max_length=15)
    celular = forms.CharField(max_length=12)
    direccion = forms.CharField(max_length=40)
    fecha_nacimiento = forms.DateTimeField(
        input_formats=['%d/%m/%Y'], 
        widget=CalendarioInput()
    )

    class Meta:
        model = Cliente
        fields = '__all__'

class SocioActualizar(forms.ModelForm):

    fecha_renovacion= forms.DateField(input_formats=settings.DATE_INPUT_FORMATS, widget=CalendarioInput())

    class Meta:
        model = Socio
        fields = ['membresia','fecha_renovacion']

    def __init__(self, id_socio, *args, **kwargs):
        super(SocioActualizar, self).__init__(*args, **kwargs)
        socio = Socio.objects.get(id=id_socio)
        self.fields['fecha_renovacion'].initial  = socio.fecha_renovacion.strftime('%d/%m/%Y')

clientes_socios/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from datetime import datetime
from .forms import *
from .models import *

class ListarMembresias(ListView):

    model = Membresia


class CrearMembresia(SuccessMessageMixin,CreateView):
    model = Membresia
    form = MembresiaCreateForm
    success_message = 'Membresia Creada Correctamente !'
    fields = '__all__'

    # Redireccionamos a la vista con la lista de servicios
    def get_success_url(self):        
        return reverse('clientes_socios:membresias-list')

class MembresiaDetalle(DetailView): 
    model = Membresia

class MembresiaActualizar(SuccessMessageMixin, UpdateView): 
    model = Membresia
    form = Membresia
    fields = "__all__"
    success_message = 'Membresia Actualizada Correctamente !'
 
    def get_success_url(self):               
        return reverse('clientes_socios:membresias-list')

class MembresiaEliminar(SuccessMessageMixin, DeleteView): 
    model = Membresia 
    form = Membresia
    fields = "__all__"     
 
    # Redireccionamos a la página principal luego de eliminar un registro o postre
    def get_success_url(self): 
        success_message = 'Membresia Eliminada Correctamente !'
        messages.success (self.request, (success_message))       
        return reverse('clientes_socios:membresias-list')


class ListarSocios(ListView):

    model = Socio


class CrearSocio(CreateView):
    model = Socio
    form_class = SocioCreateForm
    # success_message = 'Socio Creado Correctamente !'

    def form_valid(self,form):
        self.object = form.save(commit = False)
        cedula = self.kwargs.pop('cedula')
        self.object.cliente= get_object_or_404(Cliente, cedula=cedula)
        self.object.save()
        return super(CrearSocio, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(CrearSocio,self).get_form_kwargs()
        cedula = self.kwargs['cedula']
    #    # y lo envias al formulario, no se como esperas recibirlo en el formulario, pero si en el init aceptas un pk, lo envias así.
        kwargs['cliente'] = cedula
        return kwargs

    def get_success_url(self):        
        return reverse('clientes_socios:socios-list')

class SocioDetalle(DetailView): 
    model = Socio

class SocioActualizar(SuccessMessageMixin, UpdateView): 
    model = Socio
    form_class = SocioActualizar
    success_message = 'Socio Actualizado Correctamente !'
 
    def get_form_kwargs(self):
        kwargs = super(SocioActualizar,self).get_form_kwargs()
        id_socio = self.kwargs['pk']
    #    # y lo envias al formulario, no se como esperas recibirlo en el formulario, pero si en el init aceptas un pk, lo envias así.
        kwargs['id_socio'] = id_socio
        return kwargs

    def get_success_url(self):               
        return reverse('clientes_socios:socios-list')

class SocioEliminar(SuccessMessageMixin, DeleteView): 
    model = Socio 
    form = Socio
    fields = "__all__"     
    

    # Redireccionamos a la página principal luego de eliminar un registro o postre
    def get_success_url(self): 
        success_message = 'Socio Eliminado Correctamente !'
        messages.success (self.request, (success_message))       
        return reverse('clientes_socios:socios-list')

class RegistrarCliente(CreateView):
    model = Cliente
    form = ClienteCreateForm
    fields = '__all__'

    def get_success_url(self):
        opcion = self.kwargs.pop('opcion')
        cedula = self.object.cedula
        if opcion == 0:
            return reverse('clientes_socios:socio-create',kwargs={'cedula':cedula})
        else:
            return reverse('alquileres_eventos:evento-create',kwargs={'cedula':cedula})

clientes_socios/templates/clientes_socios/cliente_form.html
{% extends 'alquileres_eventos/base.html' %}

{% block content %}
        <form method="post" novalidate>
            {% csrf_token %}
            {% include 'alquileres_eventos/forms_b4.html' with form=form %}
            <div class="botones_form">
                <button type="submit" class="btn btn-dark">Registrar Cliente</button>
            </div>
          </form>
    </div>
{% endblock %}

clientes_socios/templates/clientes_socios/membresia_detalle.html
{% extends 'alquileres_eventos/base.html' %}
{% load bootstrap4 %}
{% block content %}
<style>
    h2{
        margin-top: 20px;
        margin-bottom: 20px;
    }
    p{
        font-size: 24;
    }
    .el_medio2{
            display: flex;
            /* flex-flow: row wrap;
            align-items: stretch; */
            height: 100vh;
            width: 70vw;
            padding-left: 5vw;
            padding-right: 5vw;
            background: linear-gradient(180deg, rgba(242, 98, 36, 0.0847259) 0%, rgba(242, 36, 36, 0.14827) 51.04%, rgba(242, 98, 36, 0.14827) 98.44%, rgba(242, 36, 36, 0.14827) 98.45%);
            border-radius: 8px;
            /* flex-shrink: 1; */
            position: relative;
            text-align: center;
        }
      .boton_bordo{
        background: linear-gradient(180deg, rgba(228, 22, 22, 0.849) 0%, rgba(197, 21, 12, 0.555) 52.08%, rgba(228, 22, 22, 0.849) 100%);
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.25);
        border-radius: 11px;
        }
      .fondo{
        background: linear-gradient( rgba(242, 98, 36, 0.0847259) 0%, rgba(242, 36, 36, 0.14827) 51.04%, rgba(242, 98, 36, 0.14827) 98.44%, rgba(242, 36, 36, 0.14827) 98.45%);
        position: relative;
        display: flex;
      }
      h4{
        color: #5B0101;
        align-self: center;
        margin-top: 20px;
        margin-bottom: 20px;
      }
</style>
<div class="bg-default-2 pt-16 pb-12 pt-lg-22 pb-lg-27">
    <div class="container" style="text-align: center;">
        <div class="card text-center" style="margin-top: 20px;">
            <div class="card-header">
                <h2 class="font-size-9 text-center mb-11">Detalle Membresia</h2>
            </div>
            <div class="card-body">
                <div class="row justify-content-center" style="text-align:center; align-items:center;">
                    <div class="col-5 border border-gray-500 border-2 shadow-8">
                        <p class="lead font-weight-semibold text-black-2 mb-4">Nombre:</p>
                    </div>

                    <div class="col-5 shadow-8 rounded-4 border border-gray-500 border-2">
                        <p class="lead font-weight-semibold text-black-2 mb-4">{{ object.nombre }}</p>
                    </div>
              </div>
              <div class="row justify-content-center" style="text-align:center; align-items:center;">
                    <div class="col-5 border border-gray-500 border-2 shadow-8 rounded-4">
                        <p class="lead font-weight-semibold text-black-2 mb-4">Descripcion:</p>
                    </div>

                    <div class="col-5 shadow-8 rounded-4 border border-gray-500 border-2">
                        <p class="lead font-weight-semibold text-black-2 mb-4">{{ object.descripcion }}</p>
                    </div>
                </div>
                <div class="row justify-content-center" style="text-align:center; align-items:center;">
                    <div class="col-5 border border-gray-500 border-2 shadow-8 rounded-4">
                        <p class="lead font-weight-semibold text-black-2 mb-4">Precio Anual:</p>
                    </div>

                    <div class="col-5 shadow-8 rounded-4 border border-gray-500 border-2">
                        <p class="lead font-weight-semibold text-black-2 mb-4">{{ object.precio_anual }}</p>
                    </div>
                </div>
            </div>
            <div class="card-footer text-muted">
                <div class="row justify-content-center" style="margin-top: 20px; position: relative;">
                    <div class="col-4">
                        <a class="btn btn-light boton_bordo" href="{% url 'clientes_socios:membresia-editar' pk=object.id %}">Editar Membresia</a>
                    </div>
                </div>
            </div>
          </div>
    </div>
</div>
{% endblock %}

clientes_socios/templates/clientes_socios/membresia_editar.html
{% extends 'alquileres_eventos/base.html' %}

{% block content %}
    <div class="container medio_forms">
        <form method="post" novalidate>
            {% csrf_token %}
            {% include 'alquileres_eventos/forms_b4.html' with form=form %}
            <div class="botones_form">
                <button type="submit" class="btn btn-dark">Aceptar</button>
            </div>
          </form>
    </div>
{% endblock %}

clientes_socios/templates/clientes_socios/membresia_form.html
{% extends 'alquileres_eventos/base.html' %}

{% block content %}
    <div class="container medio_forms">
        <form method="post" novalidate>
            {% csrf_token %}
            {% include 'alquileres_eventos/forms_b4.html' with form=form %}
          </form>
            <div class="botones_form">
                <button type="submit" class="btn btn-dark">Crear Membresia</button>
            </div>
    </div>
{% endblock %}

clientes_socios/templates/clientes_socios/membresias_list.html
{% extends 'alquileres_eventos/base.html' %}

{% load static %}

{% block content %}

    <style>

        .el_medio2{
            display: flex;
            /* flex-flow: row wrap;
            align-items: stretch; */
            height: 100vh;
            width: 70vw;
            padding-left: 5vw;
            padding-right: 5vw;
            background: linear-gradient(180deg, rgba(242, 98, 36, 0.0847259) 0%, rgba(242, 36, 36, 0.14827) 51.04%, rgba(242, 98, 36, 0.14827) 98.44%, rgba(242, 36, 36, 0.14827) 98.45%);
            border-radius: 8px;
            /* flex-shrink: 1; */
            position: relative;
            text-align: center;
        }

        .botones{
            display: flex;
            align-items:center;
            justify-content:center;
            align-items:flex-end;

            position: absolute;
            bottom: 0;
            left: 0;
            right: 0;
        }

        .boton_bordo{
        background: linear-gradient(180deg, rgba(228, 22, 22, 0.849) 0%, rgba(197, 21, 12, 0.555) 52.08%, rgba(228, 22, 22, 0.849) 100%);
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.25);
        border-radius: 11px;
        }

      h4{
        color: #5B0101;
        align-self: center;
        margin-top: 20px;
        margin-bottom: 20px;
      }
      .container{
      background: linear-gradient(180deg, rgba(242, 98, 36, 0.0847259) 0%, rgba(242, 36, 36, 0.14827) 51.04%, rgba(242, 98, 36, 0.14827) 98.44%, rgba(242, 36, 36, 0.14827) 98.45%);
      height: 100vh;
      text-align: center;
    }
    </style>


  <!-- <div class="container"> -->
    <div class="container">
      <h4>Membresias</h4>
    <table class="table table-bordered  table-striped table-hover">
        <thead>
          <tr>
            <th width="35%">Nombre</th>
            <th width="35%">Costo Anual</th>
            <th width="30%">Acciones</th>
          </tr>
        </thead>
        <tbody>
        
        <!-- Recorremos los objetos o registros que tenemos en nuestra tabla 'postres' y los listamos -->
        {% for membresia in object_list %}
          <tr style="border-top: 1px solid rgba(29, 28, 28, 0.3); 
          border-bottom: 1px solid rgba(29, 28, 28, 0.3); ">
            <td>{{ membresia.nombre }}</td>
            <td>{{ membresia.precio_anual }}</td>
            <td>
       
              <!-- Usaremos un formulario que realizará la tarea de eliminar un registro o postre desde la misma tabla HTML -->                        
              <form method="POST" action="{% url 'clientes_socios:membresia-eliminar' pk=membresia.id%}">
                {% csrf_token %}
                <div class="btn-group">
       
                  <!-- Creamos 3 botones que son ver, Editar y Eliminar, nos sirven para gestionar nuestros registros o postres -->
                  <a href="{% url 'clientes_socios:membresia-detalle' pk=membresia.id%}" title="Ver" type="button" class="btn btn-dark">Ver </a>
                  {% if request.user.perfil.es_gerente %}
                  <a href="{% url 'clientes_socios:membresia-editar' pk=membresia.id%}" title="Editar" type="button" class="btn btn-dark">
                    Editar</a>
                  <!-- <button class="btn btn-danger" onclick="return eliminar();" type="submit"> -->
                    <button class="btn btn-danger" onclick="return eliminar();" type="submit">
                      Eliminar
                  </button>
                  {% endif %}
                </div>
              </form>
       
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>

    <div class="row botones" style="position:relative;">
      <a class="btn btn-dark boton_bordo" id="btn-crear" href="{% url 'clientes_socios:membresia-create' %}">Agregar Membresia</a>
    </div>

  </div>
  <script type="text/javascript">
    function eliminar() {
      var x = confirm("Eliminar membresia ?");
      if (x)
        return true;
      else
        return false;
    }
  </script>

{% endblock %}

clientes_socios/templates/clientes_socios/socio_editar.html
{% extends 'alquileres_eventos/base.html' %}

{% block content %}
    <div class="container medio_forms">
        <form method="post" novalidate>
            {% csrf_token %}
            {% include 'alquileres_eventos/forms_b4.html' with form=form %}
          </form>
            <div class="botones_form">
                <button type="submit" class="btn btn-dark">Crear Membresia</button>
            </div>
    </div>
{% endblock %}

clientes_socios/templates/clientes_socios/socio_form.html
{% extends 'alquileres_eventos/base.html' %}

{% block content %}
<style>
    .botones_form{
        margin-top: 10px;
        margin-bottom: 10px;
        display: flex; 
        position: relative; 
        justify-content: center;
    }

    h4{
        margin-top: 10px;
    }

</style>

    <div class="container medio_forms">
        <h4>Cliente aun no se encuentra registrado? Registralo aqui:</h4>
        <div class="row botones" style="position: relative;">
            <a class="btn btn-dark boton_bordo" id="btn-cliente" href="{% url 'clientes_socios:cliente-create' opcion=0%}">Registrar Cliente</a>
        </div>
        <form method="post" novalidate>
            {% csrf_token %}
            {% include 'alquileres_eventos/forms_b4.html' with form=form %}
            <div class="botones_form">
                <button type="submit" class="btn btn-dark">Agregar Socio</button>
            </div>
          </form>
    </div>
{% endblock %}

clientes_socios/templates/clientes_socios/socios_list.html
{% extends 'alquileres_eventos/base.html' %}

{% load static %}

{% block content %}

    <style>

          .el_medio2{
            display: flex;
            /* flex-flow: row wrap;
            align-items: stretch; */
            height: 100vh;
            width: 70vw;
            padding-left: 5vw;
            padding-right: 5vw;
            background: linear-gradient(180deg, rgba(242, 98, 36, 0.0847259) 0%, rgba(242, 36, 36, 0.14827) 51.04%, rgba(242, 98, 36, 0.14827) 98.44%, rgba(242, 36, 36, 0.14827) 98.45%);
            border-radius: 8px;
            /* flex-shrink: 1; */
            position: relative;
            text-align: center;
            justify-content: center;
        }

        .botones{
            display: flex;
            align-items:center;
            justify-content:center;
            align-items:flex-end;

            position: absolute;
            bottom: 0;
            left: 0;
            right: 0;
        }

        .boton_bordo{
        background: linear-gradient(180deg, rgba(228, 22, 22, 0.849) 0%, rgba(197, 21, 12, 0.555) 52.08%, rgba(228, 22, 22, 0.849) 100%);
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.25);
        border-radius: 11px;
        }
        h4{
        color: #5B0101;
        /* align-self: center; */
        margin-top: 20px;
        margin-bottom: 20px;
      }
      .container{
      background: linear-gradient(180deg, rgba(242, 98, 36, 0.0847259) 0%, rgba(242, 36, 36, 0.14827) 51.04%, rgba(242, 98, 36, 0.14827) 98.44%, rgba(242, 36, 36, 0.14827) 98.45%);
      height: 100vh;
      text-align: center;
    }
    </style>


  <!-- <div class="container"> -->
    <div class="container">
      <h4>Socios del club</h4>
      <br>
    <table class="table table-bordered table-hover" style="text-align: center;">
        <thead>
          <tr>
            <th width="30%">Cliente</th>
            <th width="30%">Membresia</th>
            <th width="15%">Renovacion</th>
            <th width="25%">Acciones</th>
          </tr>
        </thead>
        <tbody>
        
        <!-- Recorremos los objetos o registros que tenemos en nuestra tabla 'postres' y los listamos -->
        {% for socio in object_list %}
          <tr style="border-top: 1px solid rgba(29, 28, 28, 0.3); 
          border-bottom: 1px solid rgba(29, 28, 28, 0.3); ">
            <td>{{ socio.cliente.nombre }}</td>
            <td>{{ socio.membresia }}</td>
            <td>{{ socio.fecha_renovacion }}</td>
            <td>
       
              <!-- Usaremos un formulario que realizará la tarea de eliminar un registro o postre desde la misma tabla HTML -->                        
              <form method="POST" action="{% url 'clientes_socios:socio-eliminar' pk=socio.id%}">
                {% csrf_token %}
                <div class="btn-group">
       
                  <!-- Creamos 3 botones que son ver, Editar y Eliminar, nos sirven para gestionar nuestros registros o postres -->
                  <a href="{% url 'clientes_socios:socio-detalle' pk=socio.id%}" title="Ver" type="button" class="btn btn-light color_medio">Ver </a>
                  <a href="{% url 'clientes_socios:socio-editar' pk=socio.id%}" title="Editar" type="button" class="btn btn-light color_medio">
                    <img src="{% static 'clientes_socios/img/lapiz.svg' %}"/></a>
                  <!-- <button class="btn btn-danger" onclick="return eliminar();" type="submit"> -->
                    <button class="btn btn-light color_medio" onclick="return eliminar();" type="submit">
                        <img src="{% static 'clientes_socios/img/basurero.svg' %}"/>
                  </button>
                </div>
              </form>
       
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>

      <div class="row botones">
        <a class="btn btn-dark boton_bordo" id="btn-crear" href="{% url 'clientes_socios:socio-create' cedula=0%}">Agregar Socio</a>
      </div>
  </div>

  <script type="text/javascript">
    function eliminar() {
      var x = confirm("Eliminar socio ?");
      if (x)
        return true;
      else
        return false;
    }
  </script>

{% endblock %}